version: '3'
services:
  database:
    container_name: database
    image: mysql:latest
    tty: true
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:19.0.3
    command: start-dev
    environment:
      DB_VENDOR: MYSQL
      DB_ADDR: database
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - 8080:8080
    depends_on:
      - database
volumes:
  database:
    driver: local
